#!/bin/bash
CURREND_DIR=$(dirname $0)
BASEDIR=$CURREND_DIR/../

mkdir -p $BASEDIR/app/
mkdir -p $BASEDIR/app/controller/
mkdir -p $BASEDIR/app/controller/public/
mkdir -p $BASEDIR/app/helper/
mkdir -p $BASEDIR/app/model/
mkdir -p $BASEDIR/app/model/base/
mkdir -p $BASEDIR/app/repository/
mkdir -p $BASEDIR/app/repository/base/
mkdir -p $BASEDIR/app/tmpl/
mkdir -p $BASEDIR/app/tmpl/fonts/
mkdir -p $BASEDIR/app/tmpl/haml/
mkdir -p $BASEDIR/app/tmpl/haml/public/
mkdir -p $BASEDIR/app/tmpl/sass/
mkdir -p $BASEDIR/app/tmpl/sass/public/
mkdir -p $BASEDIR/app/tmpl/sass/public/modules/
mkdir -p $BASEDIR/app/tmpl/sass/public/partials/
touch $BASEDIR/app/tmpl/sass/public/modules/_all.scss
touch $BASEDIR/app/tmpl/sass/public/partials/_base.scss
mkdir -p $BASEDIR/app/tmpl/sass/public/vendor/
mkdir -p $BASEDIR/app/tmpl/script/
mkdir -p $BASEDIR/app/tmpl/script/public/
mkdir -p $BASEDIR/app/tmpl/script/vendor/
mkdir -p $BASEDIR/app/vendor/
mkdir -p $BASEDIR/app/view/
mkdir -p $BASEDIR/app/view/public/
mkdir -p $BASEDIR/cache/
mkdir -p $BASEDIR/cache/haml/
mkdir -p $BASEDIR/config/
mkdir -p $BASEDIR/db/
touch $BASEDIR/db/migration.status
mkdir -p $BASEDIR/db/migrate/
mkdir -p $BASEDIR/public/
mkdir -p $BASEDIR/public/css/
mkdir -p $BASEDIR/public/fonts/
mkdir -p $BASEDIR/public/img/
mkdir -p $BASEDIR/public/css/
mkdir -p $BASEDIR/public/js/
